Install tensorflow

In [4]:
pip install tensorflow

Import Tensorflow

In [ ]:
import tensorflow as tf
print(tf.__version__)

tf.function and AutoGraph

In [2]:
a = tf.constant([2], name='constant_a')
b = tf.constant([3], name='constant_b')

In [5]:
print(type(a))
tf.print(a.numpy()[0])

<class 'tensorflow.python.framework.ops.EagerTensor'>
2


In [6]:
@tf.function
def add(a,b):
    c = tf.add(a,b)
    print(c)
    return(c)

In [8]:
result = add(a,b)
tf.print(result[0])

Tensor("Add:0", shape=(1,), dtype=int32)
5


Defining multidimensional arrays using TensorFlow

In [9]:
scalar = tf.constant(2)
vector = tf.constant([5,6,2])
matrix = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
tensor = tf.constant([ [[1,2,3],[2,3,4],[3,4,5]], [[4,5,6],[5,6,7],[6,7,8]], [[7,8,9],[8,9,10],[9,10,11]] ])

print ("Scalar (1 entry):\n %s \n" % scalar)

print ("Vector (3 entries) :\n %s \n" % vector)

print ("Matrix (3x3 entries):\n %s \n" % matrix)

print ("Tensor (3x3x3 entries) :\n %s \n" % tensor)

Scalar (1 entry):
 tf.Tensor(2, shape=(), dtype=int32) 

Vector (3 entries) :
 tf.Tensor([5 6 2], shape=(3,), dtype=int32) 

Matrix (3x3 entries):
 tf.Tensor(
[[1 2 3]
 [2 3 4]
 [3 4 5]], shape=(3, 3), dtype=int32) 

Tensor (3x3x3 entries) :
 tf.Tensor(
[[[ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]]

 [[ 4  5  6]
  [ 5  6  7]
  [ 6  7  8]]

 [[ 7  8  9]
  [ 8  9 10]
  [ 9 10 11]]], shape=(3, 3, 3), dtype=int32) 



tf.shape returns the shape of our data structure

In [12]:
print('shape of scalar is %s\n', scalar.shape)
print('shape of scalar is %s\n', vector.shape)
print('shape of scalar is %s\n', matrix.shape)
print('shape of scalar is %s\n', tensor.shape)

shape of scalar is %s
 ()
shape of scalar is %s
 (3,)
shape of scalar is %s
 (3, 3)
shape of scalar is %s
 (3, 3, 3)


In [15]:
matrix_one = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
matrix_two = tf.constant([[2,2,2],[2,2,2],[2,2,2]])

@tf.function
def add(a, b):
    res = tf.add(a, b)
    return res


print ("Defined using tensorflow function :")
add_1_operation = add(matrix_one, matrix_two)
print(add_1_operation)
print ("Defined using normal expressions :")
add_2_operation = matrix_one + matrix_two
print(add_2_operation)

Defined using tensorflow function :
tf.Tensor(
[[3 4 5]
 [4 5 6]
 [5 6 7]], shape=(3, 3), dtype=int32)
Defined using normal expressions :
tf.Tensor(
[[3 4 5]
 [4 5 6]
 [5 6 7]], shape=(3, 3), dtype=int32)


In [17]:
@tf.function
def matmul(a, b):
    res = tf.matmul(a, b)
    return res


mul_operation = matmul(matrix_one, matrix_two)

print ("Defined using tensorflow function :")
print(mul_operation)

Defined using tensorflow function :
tf.Tensor(
[[12 12 12]
 [18 18 18]
 [24 24 24]], shape=(3, 3), dtype=int32)


Variables

In [31]:
v =tf.Variable(0)
v.numpy()

0

In [32]:
@tf.function
def increment_by_one(v):
    v = tf.add(v,1)
    return v

In [33]:
for i in range(3):
    w = increment_by_one(w)
    print(w.numpy())

5
6
7


Operations

tf.constant, tf.matmul, tf.add, tf.nn.sigmoid are some of the operations in TensorFlow.

In [37]:
a = tf.constant([5])
b = tf.constant([2])
c = tf.add(a,b)
d = tf.subtract(a,b)

print ('Additon of a and b =: %s' % c.numpy())
    
print ('Substraction of a and b =: %s' % d.numpy())

Additon of a and b =: [7]
Substraction of a and b =: [3]
